/* eslint-disable @typescript-eslint/explicit-function-return-type */
import { ForbiddenException, NotFoundException } from '@nestjs/common';
import { ListingAssetRepository, ListingAssetService, ListingAssetStorage, ListingAssetSubjectAuthorizer, type ListingAsset } from './media.contracts';
class Assets extends ListingAssetRepository { rows = new Map<string, ListingAsset>(); async create(x: Omit<ListingAsset, 'id' | 'published'>) { const row = { ...x, id: 'asset', published: false }; this.rows.set(row.id, row); return row; } async save(x: ListingAsset) { this.rows.set(x.id, x); return x; } async find(id: string) { return this.rows.get(id) ?? null; } async listPublished(t: 'property' | 'room', id: string) { return [...this.rows.values()].filter((x) => x.subjectType === t && x.subjectId === id && x.published && x.status === 'ready'); } }
class Subjects extends ListingAssetSubjectAuthorizer { allowed = true; async assertOwns() { if (!this.allowed) throw new NotFoundException(); } }
class Storage extends ListingAssetStorage { async createUploadTarget() { return { uploadUrl: 'provider-neutral-target' }; } }
describe('listing asset boundary', () => {
  it('requires ownership and keeps upload provider-neutral', async () => { const assets = new Assets(), subjects = new Subjects(), service = new ListingAssetService(assets, subjects, new Storage()); await expect(service.beginUpload('owner', { subjectType: 'room', subjectId: 'room', provider: 'test', bucket: 'private', objectKey: 'key', originalName: 'a.jpg', contentType: 'image/jpeg', sizeBytes: 1 })).resolves.toMatchObject({ uploadedBy: 'owner', published: false, uploadUrl: 'provider-neutral-target' }); subjects.allowed = false; await expect(service.beginUpload('other', { subjectType: 'room', subjectId: 'room', provider: 'test', bucket: 'private', objectKey: 'bad', originalName: 'a.jpg', contentType: 'image/jpeg', sizeBytes: 1 })).rejects.toBeInstanceOf(NotFoundException); });
  it('only exposes ready published assets and ownership-checks private access', async () => { const assets = new Assets(), subjects = new Subjects(), service = new ListingAssetService(assets, subjects, new Storage()); const asset = await service.beginUpload('owner', { subjectType: 'property', subjectId: 'property', provider: 'test', bucket: 'private', objectKey: 'key', originalName: 'a.jpg', contentType: 'image/jpeg', sizeBytes: 1 }); await expect(service.publish('owner', asset.id)).rejects.toBeInstanceOf(ForbiddenException); assets.rows.set(asset.id, { ...asset, status: 'ready' }); await service.publish('owner', asset.id); await expect(service.listPublic('property', 'property')).resolves.toHaveLength(1); await expect(service.privateAsset('other', asset.id)).rejects.toBeInstanceOf(NotFoundException); });
});
